version: "3"

services:
  client:
    command: ["sleep", "10000"]
    container_name: "robo-client"
    image: "teleporttacos/client:v5"
    depends_on:
      - server
    environment:
      API_SERVER_URL: "server"
      GRPC_SERVER_LISTEN_PORT: "9999"
    networks:
      demo:
        aliases: 
          - "robo-client"
    volumes:
        - "./:/root/go"

  scylla-node1:
    container_name: scylla-node1
    image: scylla-node:v1
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    # volumes:
    #   - "./scylla_configs/scylla.yaml:/etc/scylla/scylla.yaml"
    #   - "./scylla_configs/cassandra-rackdc.properties.rk1:/etc/scylla/cassandra-rackdc.properties"
    #   - "./scylla_configs/mutant-data.txt:/mutant-data.txt"
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: "1G"
    networks:
      demo:

  scylla-node2:
    container_name: scylla-node2
    image: scylla-node:v1
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    # volumes:
    #   - "./scylla_configs/scylla.yaml:/etc/scylla/scylla.yaml"
    #   - "./scylla_configs/cassandra-rackdc.properties.rk2:/etc/scylla/cassandra-rackdc.properties"
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: "1G"
    networks:
      demo:

  scylla-node3:
    container_name: scylla-node3
    image: scylla-node:v1
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    # volumes:
    #   - "./scylla_configs/scylla.yaml:/etc/scylla/scylla.yaml"
    #   - "./scylla_configs/cassandra-rackdc.properties.rk3:/etc/scylla/cassandra-rackdc.properties"
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: "1G"
    networks:
      demo:

  server:
    command: ["sleep", "10000"]
    container_name: "server"
    image: "teleporttacos/server:v5"
    depends_on:
      - scylla-node1
      - scylla-node2
      - scylla-node3
    environment:
      GRPC_SERVER_LISTEN_PORT: "9999"
      HTTP_SERVER_LISTEN_PORT: "9080"
      # SCYLLA_SERVERS: '"scylla-node1", "scylla-node2, "scylla-node3"'
    networks:
      demo:
        aliases: 
          - "server"
    ports:
      - 9080:9080
    volumes:
        - "./:/root/go"

networks:
  demo:
    driver: bridge