version: '3'

tasks:
  # build the proto file for go
  proto:
    cmds:
      - protoc -I=./proto --go_out=./proto/ --go-grpc_opt=paths=source_relative --go-grpc_out=require_unimplemented_servers=false:./proto/pb ./proto/tacos.proto

  build-server:
    cmds:
      - docker build -t teleporttacos:v1 -f ./cmd/server/Dockerfile .

dir: '{{.USER_WORKING_DIR}}'
    
